### ISSUE TITLE
Chore: Connect issue number to commits

### ISSUE THREAD

**Issue by everGreenGH** [everGreenGH/pengtoshi-dapp-boilerplate#1]
### Task

**Automate adding issue number in commit message** to connect commit and issues.

- [x] Create issue template
- [x] Change `prepare-commit-msg.sh` script to get issue number and add it to commit msg
- [x] Change `commitlint.config.ts` file to allow issue number in commit msg
